### ISSUE TITLE
New reference design release with fixed SAT noise and LAT beams

### ISSUE THREAD

**Issue by zonca** [CMB-S4/s4_design_sim_tool#13]
* [x] New pole SAT simulations available at `/global/cscratch1/sd/keskital/s4sim/reference_tool/out`
* [x] wait for https://github.com/CMB-S4/s4sim/pull/8 to be merged
* [x] update the hardware configuration dump https://github.com/CMB-S4/s4_design_sim_tool/blob/master/cmbs4_tophat.h5 and crosscheck with tables in DSR
* [x] implement CMB tensor from https://github.com/simonsobs/so_pysm_models/issues/48#issuecomment-635722659
* [x] rerun the input sky https://github.com/CMB-S4/s4mapbasedsims/tree/master/202002_foregrounds_extragalactic_cmb_tophat
* [x] decide if we want to adjust the atmosphere simulations #2 
* [x] process the input sky in time domain
* [x] implement processing of hitmaps and white noise covariance matrices https://github.com/CMB-S4/s4_design_sim_tool/issues/9
* [ ] check the CIB https://github.com/CMB-S4/s4mapbasedsims/issues/3
* [x] rerun the reference simulation tool for r=0 and 3e-3
* [ ] validation of the run

@keskitalo @smsimon

**Comment by zonca** [comment]
CMB tensor modes implemented, ran a test simulation for SAT with r=1e-3 (will use 3e-3 for production run), scale is in uK_CMB, seems reasonable given input in https://github.com/simonsobs/so_pysm_models/issues/48#issuecomment-637691952:

![image](https://user-images.githubusercontent.com/383090/83559135-eaec7180-a4c8-11ea-850c-59c4e23f1f85.png)

**Comment by jdborrill** [comment]
I thought we had settled on 0, 1-e3, and 1e-2 to span the range of interest.

Julian

**Comment by zonca** [comment]
@jdborrill see https://github.com/simonsobs/so_pysm_models/issues/48

**Comment by zonca** [comment]
let's assume https://github.com/CMB-S4/s4sim/pull/8 is fine, beams are final, noise not yet, but I'm not using noise directly so it should be fine.
I'll use the tip of that branch as the instrument model, commit hash `c57d15d3ee9beb453cc600435f7eba8d08ff3dcd`

Exported values:

## ULFL1
Bandpass [GHz] low,center,high:  17.5 20.0 22.5
Beam [arcmin]:  10.0
## LFL1
Bandpass [GHz] low,center,high:  24.0 27.0 30.0
Beam [arcmin]:  7.4
## LFL2
Bandpass [GHz] low,center,high:  30.0 39.0 48.0
Beam [arcmin]:  5.1
## LFS1
Bandpass [GHz] low,center,high:  25.5 30.0 34.5
Beam [arcmin]:  72.8
## LFS2
Bandpass [GHz] low,center,high:  34.0 40.0 46.0
Beam [arcmin]:  72.8
## MFL1
Bandpass [GHz] low,center,high:  75.5 93.0 110.5
Beam [arcmin]:  2.2
## MFL2
Bandpass [GHz] low,center,high:  125.0 145.0 165.0
Beam [arcmin]:  1.4
## MFLS1
Bandpass [GHz] low,center,high:  74.8 85.0 95.2
Beam [arcmin]:  25.5
## MFLS2
Bandpass [GHz] low,center,high:  129.1 145.1 161.0
Beam [arcmin]:  25.5
## MFHS1
Bandpass [GHz] low,center,high:  83.6 95.0 106.4
Beam [arcmin]:  22.7
## MFHS2
Bandpass [GHz] low,center,high:  138.0 155.1 172.1
Beam [arcmin]:  22.7
## HFL1
Bandpass [GHz] low,center,high:  195.0 225.0 255.0
Beam [arcmin]:  1.0
## HFL2
Bandpass [GHz] low,center,high:  255.5 278.0 300.5
Beam [arcmin]:  0.9
## HFS1
Bandpass [GHz] low,center,high:  195.8 220.0 244.2
Beam [arcmin]:  13.0
## HFS2
Bandpass [GHz] low,center,high:  240.3 270.0 299.7
Beam [arcmin]:  13.0

**Comment by zonca** [comment]
@smsimon I was comparing the SAT beams from `s4sim` (see above) to the ones in the DSR table.
I think `MFLS` and `MFHS` are switched, can you crosscheck?

![image](https://user-images.githubusercontent.com/383090/84095776-07027e00-a9b5-11ea-996c-664e549e6b12.png)

Or is the table in the DSR that has the wrong column headers? how is the one with lower frequency named High?

**Comment by zonca** [comment]
I assumed `s4sim` figures were correct and produced a new set of input sky simulations.
@keskitalo can you run them through the time domain simulations?
the 4 set of maps you need are described in https://github.com/CMB-S4/s4mapbasedsims/tree/master/202006_foregrounds_extragalactic_cmb_tophat#combined-maps, basically just changed the base folder. The SAT maps are ready, I am running the combining script for the LAT, it will be done overnight.

**Comment by smsimon** [comment]
They are right in s4sim. The column headers in the DSR are wrong here (95/155 is certainly higher than 85/145!). The DSR spreadsheet has them correctly labeled, and it makes physical sense.

**Comment by zonca** [comment]
ok, @keskitalo has executed the time domain simulations, he needs to rerun the SAT.
So for now I have executed the LAT simulations, need validation.

**Comment by zonca** [comment]
@keskitalo discovered issue in LAT Chile noise and reran the TOD simulations.

Need to run the tool again pointing at:

    /global/cscratch1/sd/keskital/s4sim/reference_tool/out_v1

and then go with the validation and release.

**Comment by zonca** [comment]
ok I launched atmo + noise again with the new input maps. I'll use the foreground and CMB I already ran before, as I believe nothing changed, (please @keskitalo let me know if this is wrong).

I'm also preparing another CMB tensor set of maps which include TT and EE.

**Comment by zonca** [comment]
@keskitalo I have rerun the CMB tensors including also TT and EE, I have replaced the old ones in the folder:
   
```
/global/cscratch1/sd/zonca/cmbs4/map_based_simulations/202006_foregrounds_extragalactic_cmb_tophat/4096/cmb_tensor/0000
```

and the `512` folder.
Can you please rerun the TOD simulations of those?

**Comment by keskitalo** [comment]
I'll get right on it.

**Comment by keskitalo** [comment]
@zonca these maps are ring-ordered, unlike the earlier batch. The pipeline will only work with nested maps. Should I re-order the maps or is it easy for you to do?

**Comment by keskitalo** [comment]
I am reordering the maps. They will appear here: `/global/cscratch1/sd/keskital/s4sim/reference_tool/cmb_tensor` if you want copies in your directory.

**Comment by zonca** [comment]
sorry @keskitalo completely forgot about ordering, I actually modified `mapsims` to always save nested from now on so this won't happen again.

**Comment by keskitalo** [comment]
Looks like the maps are in uK_CMB. Is it difficult for you to account for that during the co-add?

**Comment by zonca** [comment]
maps from mapsims are always in `uK_CMB`, in `s4_design_sim_tool` instead input foregrounds/CMB are in `uK_CMB`, input noise and atmo are `K_CMB`, outputs are `K_CMB`.

**Comment by keskitalo** [comment]
The new tensor maps are now in place under `out_v1`.

**Comment by zonca** [comment]
thanks @keskitalo can you please fix permissions? e.g. `/global/cscratch1/sd/keskital/s4sim/reference_tool/out_v1/00000000/chile_cmb-tensors_LAT_HFL1_filtered_telescope_all_time_all_bmap.fits`

**Comment by keskitalo** [comment]
Oops! Done.

**Comment by zonca** [comment]
ok, @keskitalo @jdborrill, the new release is ready at:

`/global/cscratch1/sd/zonca/cmbs4/s4refsimtool`

next I'll implement weighting of hitmaps and noise cov matrices (the input ones are in `/global/cscratch1/sd/keskital/s4sim/reference_tool/out_v1`), then I'll proceed with proper validation.

@cbischoff would you like to start checking those maps?

Docs about the release are at https://github.com/CMB-S4/s4mapbasedsims/tree/master/202006_reference_design

**Comment by zonca** [comment]
Reran the atmosphere + noise simulations with the fix on efficiency provided by @keskitalo. Now also have hitmaps and noise covariance matrices as implemented in #9.
Working now on validation.

**Comment by zonca** [comment]
see #14 for validation
